#!/usr/bin/env python3
"""Full Telegram-style ticker report with required DailyEdge images."""
from __future__ import annotations

import argparse
import json
import math
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
OUTPUT_DIR = ROOT / "output"
sys.path.insert(0, str(SCRIPT_DIR))

import gate_hook
import ledger
import levels
import market_regime
import outcome_lab
import report_images
import universe_scanner


def _utcstamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def fetch_df(ticker: str, period: str = "6mo", interval: str = "1d") -> pd.DataFrame:
    return outcome_lab.fetch(ticker, period, interval)


def add_features(df: pd.DataFrame) -> pd.DataFrame:
    f = df.copy()
    f["EMA9"] = f["Close"].ewm(span=9, adjust=False).mean()
    f["EMA20"] = f["Close"].ewm(span=20, adjust=False).mean()
    f["SMA50"] = f["Close"].rolling(50).mean()
    f["RSI14"] = outcome_lab.rsi(f["Close"])
    f["ATR14"] = outcome_lab.atr(f)
    return f


def render_required_images(
    ticker: str,
    df: pd.DataFrame,
    action: str,
    trigger: float | None,
    entry: float | None,
    stop: float | None,
    target: float | None,
    output_dir: str | Path = OUTPUT_DIR,
    render_mc_placeholder: bool = False,
) -> dict[str, str]:
    outdir = Path(output_dir)
    outdir.mkdir(parents=True, exist_ok=True)
    ts = _utcstamp()
    original_fetch = report_images._fetch
    report_images._fetch = lambda tk, period="6mo", interval="1d": df.copy()
    try:
        daily_path = report_images.render_daily_setup(ticker, trigger=trigger, stop=stop, target=target, entry=entry, action=action, outdir=outdir)
    finally:
        report_images._fetch = original_fetch
    paths = {"daily_setup": str(daily_path), "daily_setup_latest": str(outdir / f"{ticker}_latest_daily_setup.png")}

    f = add_features(df).tail(130)
    price = float(f["Close"].iloc[-1])
    plt.style.use("dark_background")
    fig, axes = plt.subplots(3, 1, figsize=(12.8, 8.2), sharex=True, gridspec_kw={"height_ratios": [3, 1, 1]})
    ax, av, ar = axes
    x = f.index
    ax.plot(x, f["Close"], color="#e6edf3", lw=1.8, label="Close")
    ax.plot(x, f["EMA9"], color="#f2cc60", lw=1.0, label="EMA9")
    ax.plot(x, f["EMA20"], color="#58a6ff", lw=1.0, label="EMA20")
    ax.plot(x, f["SMA50"], color="#a371f7", lw=1.0, label="SMA50")
    for name, val, color in [
        ("trigger", trigger, "#ff7b72"),
        ("entry", entry, "#3fb950"),
        ("stop", stop, "#ff5555"),
        ("T1", target, "#56d364"),
        ("T2", entry + 2 * (target - entry) if entry and target else None, "#2ea043"),
    ]:
        if val is not None and math.isfinite(float(val)):
            ax.axhline(float(val), color=color, ls="--", lw=0.9)
            ax.text(x[-1], float(val), f" {name} {float(val):.2f}", color=color, va="center", fontsize=8)
    try:
        sr = levels.detect_all(df).get("sr", [])[:3]
        for zone in sr:
            ax.axhspan(zone["low"], zone["high"], color="#388bfd", alpha=0.08)
    except Exception:
        pass
    ax.set_title(f"{ticker} ${price:.2f} — {action} — {f.index[-1].date()}")
    ax.legend(loc="upper left", fontsize=8)
    ax.grid(alpha=0.15)
    av.bar(x, f["Volume"], color="#6e7681", width=1.0)
    av.set_ylabel("Vol")
    ar.plot(x, f["RSI14"], color="#f778ba")
    ar.axhline(70, color="#ff7b72", lw=0.8, alpha=0.6)
    ar.axhline(30, color="#3fb950", lw=0.8, alpha=0.6)
    ar.set_ylabel("RSI")
    ar.xaxis.set_major_formatter(mdates.DateFormatter("%m-%d"))
    fig.tight_layout()
    daily = outdir / f"{ticker}_{ts}_legacy_daily_setup.png"
    fig.savefig(daily, dpi=100, facecolor="#0d1117")
    plt.close(fig)
    if render_mc_placeholder:
        fig, ax = plt.subplots(figsize=(12.8, 5.0))
        ax.plot(f.index, f["Close"], color="#58a6ff")
        ax.set_title(f"{ticker} SCENARIO DISTRIBUTION — NOT A FORECAST — excluded from confidence")
        ax.text(0.5, 0.5, "MC fan generated by chart_simulation.py in live reports\nPlaceholder for test/offline mode", transform=ax.transAxes, ha="center", va="center", fontsize=14)
        ax.grid(alpha=0.15)
        fig.tight_layout()
        mc = outdir / f"{ticker}_{ts}_mc_fan.png"
        fig.savefig(mc, dpi=100, facecolor="#0d1117")
        plt.close(fig)
        paths["mc_fan"] = str(mc)

        fig, ax = plt.subplots(figsize=(12.8, 5.2))
        rel = f["Close"] / f["Close"].iloc[0]
        ax.plot(f.index, rel, label=f"{ticker}/self baseline", color="#56d364")
        ax.plot(f.index, rel.rolling(20).mean(), label="20d relative MA", color="#f2cc60")
        ax.set_title("RS PANEL — offline/test placeholder")
        ax.grid(alpha=0.15)
        ax.legend(fontsize=8)
        fig.tight_layout()
        rs = outdir / f"RS_PANEL_{ticker}_{ts}.png"
        fig.savefig(rs, dpi=100, facecolor="#0d1117")
        plt.close(fig)
        paths["rs_panel"] = str(rs)
    return paths


def render_rs_panel(tickers: list[str], frames: dict[str, pd.DataFrame], output_dir: str | Path = OUTPUT_DIR) -> str:
    outdir = Path(output_dir)
    outdir.mkdir(parents=True, exist_ok=True)
    ts = _utcstamp()
    plt.style.use("dark_background")
    fig, ax = plt.subplots(figsize=(12.8, 5.2))
    spy = frames.get("SPY")
    smh = frames.get("SMH")
    for tk in tickers[:3]:
        df = frames.get(tk)
        if df is None or df.empty:
            continue
        base = df["Close"].tail(130)
        if spy is not None and not spy.empty:
            ratio = (base / spy["Close"].reindex(base.index).ffill()).dropna()
            ax.plot(ratio.index, ratio / ratio.iloc[0], label=f"{tk}/SPY")
        if smh is not None and not smh.empty:
            ratio = (base / smh["Close"].reindex(base.index).ffill()).dropna()
            ax.plot(ratio.index, ratio / ratio.iloc[0], ls="--", label=f"{tk}/SMH")
    ax.set_title("RS PANEL — top scanner candidates vs SPY/SMH")
    ax.grid(alpha=0.15)
    ax.legend(fontsize=8)
    fig.tight_layout()
    path = outdir / f"RS_PANEL_{ts}.png"
    fig.savefig(path, dpi=100, facecolor="#0d1117")
    plt.close(fig)
    return str(path)


def days_to_earnings(ticker: str) -> int | None:
    try:
        import yfinance as yf
        cal = yf.Ticker(ticker).calendar
        if cal is None or len(cal) == 0:
            return None
        # yfinance variants: DataFrame or dict
        dt = None
        if isinstance(cal, dict):
            vals = cal.get("Earnings Date") or cal.get("EarningsDate")
            if isinstance(vals, (list, tuple)) and vals:
                dt = vals[0]
            else:
                dt = vals
        elif hasattr(cal, "index"):
            for key in ["Earnings Date", "EarningsDate"]:
                if key in cal.index:
                    v = cal.loc[key].iloc[0] if hasattr(cal.loc[key], "iloc") else cal.loc[key]
                    dt = v[0] if isinstance(v, (list, tuple)) else v
                    break
        if dt is None:
            return None
        d = pd.Timestamp(dt).tz_localize(None).date()
        return (d - datetime.now().date()).days
    except Exception:
        return None


def run_chart_simulation(ticker: str) -> str | None:
    try:
        proc = subprocess.run(
            [sys.executable, str(SCRIPT_DIR / "chart_simulation.py"), ticker, "--period", "1y", "--interval", "1d", "--days", "30", "--paths", "5000", "--backend", "auto"],
            cwd=str(ROOT), text=True, capture_output=True, timeout=300, check=True,
        )
        data = json.loads(proc.stdout)
        return data.get("chart_png")
    except Exception:
        return None


def build_full_report(ticker: str, scanner_row: dict[str, Any] | None = None, scanner_regime: dict[str, Any] | None = None) -> dict[str, Any]:
    df = fetch_df(ticker)
    f = add_features(df)
    latest = f.iloc[-1]
    price = float(latest["Close"])
    trigger = scanner_row.get("breakout_trigger") if scanner_row else float(f["High"].rolling(20).max().shift().iloc[-1])
    action = scanner_row.get("action") if scanner_row else "REPORT"
    entry = trigger if scanner_row and action == "SET_ALERT" else price
    atr = float(latest["ATR14"])
    if scanner_row and scanner_row.get("gate"):
        stop = float(scanner_row["gate"]["stop"])
        target = float(scanner_row["gate"]["target"])
        gate_stamp = scanner_row["gate"].get("stamp") or gate_hook.state_stamp(action, entry=entry, stop=stop, target=target, atr=atr)
    else:
        stop = entry - 1.5 * atr
        target = entry + 2.0 * (entry - stop)
        gate_stamp = gate_hook.state_stamp(action, entry=entry, stop=stop, target=target, atr=atr)
    regime = scanner_regime
    if regime is None:
        regime_frames, _ = market_regime.fetch_regime_frames(ticker)
        regime = market_regime.score_market_regime(regime_frames, sector_etf=market_regime.sector_etf_for_ticker(ticker))
    er_days = days_to_earnings(ticker) if not scanner_row else scanner_row.get("days_to_earnings") or days_to_earnings(ticker)
    images = render_required_images(ticker, df, action, trigger, entry, stop, target)
    try:
        images["rs_panel"] = report_images.render_rs_panel(ticker, outdir=OUTPUT_DIR)
    except Exception:
        pass
    mc = run_chart_simulation(ticker)
    if mc:
        images["mc_fan"] = mc
    report = {
        "ticker": ticker,
        "price": price,
        "timestamp": str(f.index[-1]),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "action": action,
        "gate_stamp": gate_stamp,
        "regime": regime,
        "trigger": trigger,
        "entry": entry,
        "stop": stop,
        "target": target,
        "rsi14": scanner_row.get("rsi14") if scanner_row and scanner_row.get("rsi14") is not None else (float(latest["RSI14"]) if pd.notna(latest["RSI14"]) else None),
        "atr14": atr,
        "days_to_earnings": er_days,
        "ext50d_pct": scanner_row.get("ext_pct_vs_sma50") if scanner_row else None,
        "ann_vol_pct": scanner_row.get("ann_vol_pct") if scanner_row else None,
        "rel_volume": scanner_row.get("rel_volume") if scanner_row else None,
        "rs20_vs_spy_pct": scanner_row.get("rs20_vs_spy_pct") if scanner_row else None,
        "rs63_vs_spy_pct": scanner_row.get("rs63_vs_spy_pct") if scanner_row else None,
        "sector": ledger.sector_cluster(ticker),
        "images": images,
    }
    return report


def format_report(report: dict[str, Any]) -> str:
    reg = report["regime"]
    ev_line = "EVIDENCE: INCUBATION | ledger n 0 | backtest unavailable | established no"
    try:
        ev = json.loads((OUTPUT_DIR / "evidence.json").read_text())
        pooled, base = ev.get("pooled", {}), ev.get("baseline", {})
        ev_line = (
            f"EVIDENCE: INCUBATION | ledger n 0 | backtest n {pooled.get('n', 0)}, "
            f"point {float(pooled.get('e', 0)):+.2f} vs baseline {float(base.get('e', 0)):+.2f}; "
            f"cons {float(pooled.get('ec', 0)):+.2f} vs baseline {float(base.get('ec', 0)):+.2f} | "
            f"established {'yes' if ev.get('edge_established') else 'no'}"
        )
    except Exception:
        pass
    lines = [
        f"{report['ticker']} ${report['price']:.2f} | as of bar {report['timestamp']} close | generated {report.get('generated_at')} | regime: {reg.get('regime')} score {reg.get('weighted_score')}",
        f"{report['action']} | {report['gate_stamp']}",
        ev_line,
        f"SETUP: trigger ${float(report['trigger']):.2f}, entry ${float(report['entry']):.2f}, stop ${float(report['stop']):.2f}, target ${float(report['target']):.2f}",
        f"CONTEXT: RSI {report.get('rsi14'):.2f} | ext50d {report.get('ext50d_pct')}% | annVol {report.get('ann_vol_pct')}% | RVOL {report.get('rel_volume')} | RS20 {report.get('rs20_vs_spy_pct')}% / RS63 {report.get('rs63_vs_spy_pct')}% vs SPY | ATR ${report['atr14']:.2f} | ER in {report.get('days_to_earnings')}d | sector {report['sector']}",
        "RISK STATE: day 0R | week 0R | open risk 0R | sector positions 0/2 cap",
    ]
    for p in report["images"].values():
        lines.append(f"MEDIA:{p}")
    lines.append("Data quality: yfinance OHLCV/live helper; verify news/fundamentals separately. Analytical only, not financial advice.")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("ticker")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()
    report = build_full_report(args.ticker.upper())
    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True, default=str))
    else:
        print(format_report(report))


if __name__ == "__main__":
    main()
